=== Anluren/cppscapy/python-package/examples/network_protocols.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Root element -->
    <xs:element name="network_protocols">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="enum"/>
                    <xs:element ref="header"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Enum definition -->
    <xs:element name="enum">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="value" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="underlying_type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="uint8_t"/>
                        <xs:enumeration value="uint16_t"/>
                        <xs:enumeration value="uint32_t"/>
                        <xs:enumeration value="uint64_t"/>
                        <xs:enumeration value="8"/>
                        <xs:enumeration value="16"/>
                        <xs:enumeration value="32"/>
                        <xs:enumeration value="64"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- Enum value -->
    <xs:element name="value">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="value" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Header definition -->
    <xs:element name="header">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="field" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="description" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- Field definition -->
    <xs:element name="field">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="attributes" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="attribute" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="bit_width" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="integer"/>
                        <xs:enumeration value="enum"/>
                        <xs:enumeration value="array"/>
                        <xs:enumeration value="union"/>
                        <xs:enumeration value="variable"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="enum_type" type="xs:string" use="optional"/>
            <xs:attribute name="default" type="xs:string" use="optional"/>
            <xs:attribute name="condition" type="xs:string" use="optional"/>
            <xs:attribute name="description" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Anluren/cppscapy/examples/converted_from_hdl.xml
<network_protocols xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="network_protocols.xsd">
    <!-- Converted from HDL format -->
    <enum name="EtherType" underlying_type="uint16_t">
        <value name="IPv4" value="0x0800"/>
        <value name="IPv6" value="0x86DD"/>
        <value name="ARP" value="0x0806"/>
        <value name="MPLS" value="0x8847"/>
        <value name="VLAN" value="0x8100"/>
    </enum>
    <enum name="IPProtocol" underlying_type="uint8_t">
        <value name="ICMP" value="1"/>
        <value name="IGMP" value="2"/>
        <value name="TCP" value="6"/>
        <value name="UDP" value="17"/>
        <value name="GRE" value="47"/>
        <value name="ESP" value="50"/>
        <value name="AH" value="51"/>
        <value name="ICMPv6" value="58"/>
        <value name="OSPF" value="89"/>
        <value name="SCTP" value="132"/>
    </enum>
    <enum name="ICMPType" underlying_type="uint8_t">
        <value name="ECHO_REPLY" value="0"/>
        <value name="DEST_UNREACHABLE" value="3"/>
        <value name="SOURCE_QUENCH" value="4"/>
        <value name="REDIRECT" value="5"/>
        <value name="ECHO_REQUEST" value="8"/>
        <value name="TIME_EXCEEDED" value="11"/>
        <value name="PARAMETER_PROBLEM" value="12"/>
        <value name="TIMESTAMP_REQUEST" value="13"/>
        <value name="TIMESTAMP_REPLY" value="14"/>
    </enum>
    <enum name="DHCPMessageType" underlying_type="uint8_t">
        <value name="BOOTREQUEST" value="1"/>
        <value name="BOOTREPLY" value="2"/>
    </enum>
    <header name="EthernetHeader">
        <description>Generated EthernetHeader protocol header</description>
        <field name="dst_mac" bit_width="48" type="integer">
            <description>Dst Mac field</description>
        </field>
        <field name="src_mac" bit_width="48" type="integer">
            <description>Src Mac field</description>
        </field>
        <field name="ethertype" bit_width="16" type="enum" enum_type="EtherType">
            <description>Ethertype field</description>
        </field>
    </header>
    <header name="IPv4Header">
        <description>Generated IPv4Header protocol header</description>
        <field name="version" bit_width="4" type="integer" default="4">
            <description>Version field</description>
        </field>
        <field name="ihl" bit_width="4" type="integer" default="5">
            <description>Ihl field</description>
        </field>
        <field name="tos" bit_width="8" type="integer">
            <description>Tos field</description>
        </field>
        <field name="total_length" bit_width="16" type="integer">
            <description>Total Length field</description>
            <attributes>
                <attribute>computed</attribute>
            </attributes>
        </field>
        <field name="identification" bit_width="16" type="integer">
            <description>Identification field</description>
        </field>
        <field name="reserved" bit_width="1" type="integer" default="0">
            <description>Reserved field</description>
        </field>
        <field name="dont_fragment" bit_width="1" type="integer">
            <description>Dont Fragment field</description>
        </field>
        <field name="more_fragments" bit_width="1" type="integer">
            <description>More Fragments field</description>
        </field>
        <field name="fragment_offset" bit_width="13" type="integer">
            <description>Fragment Offset field</description>
        </field>
        <field name="ttl" bit_width="8" type="integer" default="64">
            <description>Ttl field</description>
        </field>
        <field name="protocol" bit_width="8" type="enum" enum_type="IPProtocol">
            <description>Protocol field</description>
        </field>
        <field name="header_checksum" bit_width="16" type="integer">
            <description>Header Checksum field</description>
            <attributes>
                <attribute>computed</attribute>
            </attributes>
        </field>
        <field name="src_ip" bit_width="32" type="integer">
            <description>Src Ip field</description>
        </field>
        <field name="dst_ip" bit_width="32" type="integer">
            <description>Dst Ip field</description>
        </field>
    </header>
    <header name="UDPHeader">
        <description>Generated UDPHeader protocol header</description>
        <field name="src_port" bit_width="16" type="integer">
            <description>Src Port field</description>
        </field>
        <field name="dst_port" bit_width="16" type="integer">
            <description>Dst Port field</description>
        </field>
        <field name="length" bit_width="16" type="integer">
            <description>Length field</description>
            <attributes>
                <attribute>computed</attribute>
            </attributes>
        </field>
        <field name="checksum" bit_width="16" type="integer">
            <description>Checksum field</description>
            <attributes>
                <attribute>computed</attribute>
            </attributes>
        </field>
    </header>
    <header name="TCPHeader">
        <description>Generated TCPHeader protocol header</description>
        <field name="src_port" bit_width="16" type="integer">
            <description>Src Port field</description>
        </field>
        <field name="dst_port" bit_width="16" type="integer">
            <description>Dst Port field</description>
        </field>
        <field name="seq_num" bit_width="32" type="integer">
            <description>Seq Num field</description>
        </field>
        <field name="ack_num" bit_width="32" type="integer">
            <description>Ack Num field</description>
        </field>
        <field name="data_offset" bit_width="4" type="integer" default="5">
            <description>Data Offset field</description>
        </field>
        <field name="reserved" bit_width="3" type="integer" default="0">
            <description>Reserved field</description>
        </field>
        <field name="flag_ns" bit_width="1" type="integer">
            <description>Flag Ns field</description>
        </field>
        <field name="flag_cwr" bit_width="1" type="integer">
            <description>Flag Cwr field</description>
        </field>
        <field name="flag_ece" bit_width="1" type="integer">
            <description>Flag Ece field</description>
        </field>
        <field name="flag_urg" bit_width="1" type="integer">
            <description>Flag Urg field</description>
        </field>
        <field name="flag_ack" bit_width="1" type="integer">
            <description>Flag Ack field</description>
        </field>
        <field name="flag_psh" bit_width="1" type="integer">
            <description>Flag Psh field</description>
        </field>
        <field name="flag_rst" bit_width="1" type="integer">
            <description>Flag Rst field</description>
        </field>
        <field name="flag_syn" bit_width="1" type="integer">
            <description>Flag Syn field</description>
        </field>
        <field name="flag_fin" bit_width="1" type="integer">
            <description>Flag Fin field</description>
        </field>
        <field name="window_size" bit_width="16" type="integer">
            <description>Window Size field</description>
        </field>
        <field name="checksum" bit_width="16" type="integer">
            <description>Checksum field</description>
            <attributes>
                <attribute>computed</attribute>
            </attributes>
        </field>
        <field name="urgent_ptr" bit_width="16" type="integer">
            <description>Urgent Ptr field</description>
        </field>
    </header>
    <header name="ICMPHeader">
        <description>Generated ICMPHeader protocol header</description>
        <field name="type" bit_width="8" type="enum" enum_type="ICMPType">
            <description>Type field</description>
        </field>
        <field name="code" bit_width="8" type="integer">
            <description>Code field</description>
        </field>
        <field name="checksum" bit_width="16" type="integer">
            <description>Checksum field</description>
            <attributes>
                <attribute>computed</attribute>
            </attributes>
        </field>
        <field name="identifier" bit_width="16" type="integer">
            <description>Identifier field</description>
        </field>
        <field name="sequence" bit_width="16" type="integer">
            <description>Sequence field</description>
        </field>
    </header>
    <header name="IPv6Header">
        <description>Generated IPv6Header protocol header</description>
        <field name="version" bit_width="4" type="integer" default="6">
            <description>Version field</description>
        </field>
        <field name="traffic_class" bit_width="8" type="integer">
            <description>Traffic Class field</description>
        </field>
        <field name="flow_label" bit_width="20" type="integer">
            <description>Flow Label field</description>
        </field>
        <field name="payload_length" bit_width="16" type="integer">
            <description>Payload Length field</description>
            <attributes>
                <attribute>computed</attribute>
            </attributes>
        </field>
        <field name="next_header" bit_width="8" type="enum" enum_type="IPProtocol">
            <description>Next Header field</description>
        </field>
        <field name="hop_limit" bit_width="8" type="integer" default="64">
            <description>Hop Limit field</description>
        </field>
        <field name="src_addr" bit_width="128" type="integer">
            <description>Src Addr field</description>
        </field>
